### PR TITLE
Update operator-sdk to v1.18

### PR DESCRIPTION
**Pull request by adambkaplan**
# Changes

Upgrade operator-sdk to v1.18, bringing in the following enhancements:

- Ability to use image digests in the released operator bundle (v1.18.0)
- Fix deployment to align with operator-sdk requirements.

# Submitter Checklist

- [x] Includes tests if functionality changed/was added
- [x] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Add `control-plane` label to operator deployment so it supports bundling with operator-sdk v1.18
```

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

Let's cut the release for v0.12.0 before we start making changes to the deployment.

**Comment by adambkaplan** [comment]
/hold cancel

v0.12.0 has been tagged, we are just waiting on the final :+1: before we release.

**Comment by adambkaplan** [comment]
/approve

Self-approving

**Comment by coreydaley** [comment]
The title of the pr says  version `1.18.0` but the code changes seem to say `1.17.0`, just want to double check.

**Comment by adambkaplan** [comment]
> The title of the pr says  version `1.18.0` but the code changes seem to say `1.17.0`, just want to double check.

This is a long-standing issue with these older operator-sdk releases. I raised this upstream previously, but they could not reproduce with the newer versions.

**Review by SaschaSchwarze0 — APPROVED** [review]
/approve
/lgtm

**Comment by adambkaplan** [comment]
Relates to #164

**Pull request merged**
