### PR TITLE
Bump dependencies to align with Build v0.12.0

### PR DESCRIPTION
**Pull request by adambkaplan**
# Changes

Update the dependencies so we can bring in shipwright-io/build v0.12.0 as a new dependency. This is needed to support #155 

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Update k8s libraries to v0.26.4, controller-runtime to v0.14.6, and tektoncd/operator to v0.67.0. ACTION REQUIRED: minimum kubernetes version is now v1.24.0
```

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

This should wait for #164 to be merged first, as it builds on top of its commits.

**Comment by adambkaplan** [comment]
/approve

Self-approving

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Pull request merged**
