### PR TITLE
upload go.mod vendor tree

### PR DESCRIPTION
**Pull request by gabemontero**
# Changes

upload vendor tree

# Submitter Checklist

- [n/a ] Includes tests if functionality changed/was added
- [n/a ] Includes docs if changes are user-facing
- [/ ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ /] Release notes block has been filled in, or marked NONE

/kind cleanup

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/approve

**Comment by gabemontero** [comment]
@SaschaSchwarze0 @mattcui any cycles to review / lgtm if you are OK with this one, so we have cross company sign off ?

**Comment by SaschaSchwarze0** [comment]
> @SaschaSchwarze0 @mattcui any cycles to review / lgtm if you are OK with this one, so we have cross company sign off ?

I can, but be aware that I never looked at any code in this repo.

/lgtm

**Pull request merged**
