### PR TITLE
Update to Go 1.17

### LINKED ISSUE #34: Update Golang to 1.17
Go 1.17 exists for a while now and the CLI is using it already. We should also update the Go version here in the operator repo.

Acceptance criteria:

- [ ] [go.mod](https://github.com/shipwright-io/operator/blob/main/go.mod) has been updated, go mod vendor was run. There will be many changes as Go 1.17 changed the format of indirect dependencies
- [ ] the [workflows](https://github.com/shipwright-io/operator/tree/main/.github/workflows) have been updated to all use 1.17.
- [ ] [Development guidelines](https://github.com/shipwright-io/operator/blob/main/docs/development/local-development.md#prerequisites) have been updated

### PR DESCRIPTION
**Pull request by vancanhuit**
# Changes

Closes #34
 
# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/master/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by adambkaplan** [comment]
@vancanhuit if possible, can you please rebase this pull request on top of the `main` branch? It looks like you did a merge instead, which will result in a commit history that may be harder to interpret.

**Comment by adambkaplan** [comment]
/hold

Waiting for v0.7.0 to be released before we update the golang version.

**Comment by vancanhuit** [comment]
> @vancanhuit if possible, can you please rebase this pull request on top of the `main` branch? It looks like you did a merge instead, which will result in a commit history that may be harder to interpret.

Yes I will try.

**Comment by adambkaplan** [comment]
@vancanhuit two items are causing the tests to fail:

1. There is a format change with go 1.17 that the deep copier isn't generating automatically. If you run `make fmt` and commit the change, I think this will fix the issue.
2. The `VERSION` variable in the Makefile conflicts with the operator version we published on OperatorHub. I submitted
 https://github.com/shipwright-io/operator/pull/52 to fix this issue. Once it merges you will need to rebase this PR to pull in the new default version.

**Comment by otaviof** [comment]
@vancanhuit thanks for the contributions! Would you please squash those two commits. Other than that, I think we are as good as done.

**Comment by vancanhuit** [comment]
@otaviof I've squashed those 2 commits.

**Comment by adambkaplan** [comment]
@vancanhuit apologies, I think this PR needs to be rebased on top of the `main` branch. The e2e test currently breaks because we are trying to add a CSV version that is the same as what exsits on operatorhub. #52 fixes this.

**Review by adambkaplan — COMMENTED** [review]
/approve

Marking this as an approved change.

**Comment by adambkaplan** [comment]
/lgtm

Running into known `opm index` issue.

**Pull request merged**
