### PR TITLE
Add dependent images as env vars

### PR DESCRIPTION
**Pull request by jkhelil**
# Changes

The operator is using release.yaml to deploy shipwright build controller, and passing it git clone, waiters images as env vars
The dependent images should be retrieved as env vars in the operator deployment, because they can be customised(built from specific base image for security reason etc)
Typically when deploying the operator via olm, we need to pass these dependent images as env vars in the csv.
This PR implement en vars dependent images

# Submitter Checklist

- [*] Includes tests if functionality changed/was added
- [*] Includes docs if changes are user-facing
- [*] Release notes block has been filled in, or marked NONE

# Release Notes
```release-note
Added new environment variables to customize Shiprwright controller installation:
- IMAGE_SHIPWRIGHT_SHIPWRIGHT_BUILD : defines the Shipwright Build Controller Image to use
- IMAGE_SHIPWRIGHT_GIT_CONTAINER_IMAGE: defines the Shipwright Git Container Image to use
- IMAGE_SHIPWRIGHT_MUTATE_IMAGE_CONTAINER_IMAGE:  defines the Shipwright Mutate Image to use
- IMAGE_SHIPWRIGHT_BUNDLE_CONTAINER_IMAGE: defines the Shipwright Bundle Image to use
- IMAGE_SHIPWRIGHT_WAITER_CONTAINER_IMAGE: defines the Shipwright Waiter Image to use
```

### CODE REVIEW

**Comment by jkhelil** [comment]
@adambkaplan ,  @HeavyWombat or @otaviof 
Please review this

**Review by otaviof — CHANGES_REQUESTED** [review]
@jkhelil could you please make the following changes?
- document how it works (`README.md`) linking with Shipwright's configuration docs
- test against the `kodata` manifest instead of generic mocked resources

Thanks in advance!

**Comment by jkhelil** [comment]
> @jkhelil could you please make the following changes?
> 
> * document how it works (`README.md`) linking with Shipwright's configuration docs
> * test against the `kodata` manifest instead of generic mocked resources
> 
> Thanks in advance!

PR updated
@otaviof please review

**Review by otaviof — APPROVED** [review]
/lgtm
/approve

**Comment by jkhelil** [comment]
/retitle Add dependent images as environment variables

**Comment by otaviof** [comment]
/assign @SaschaSchwarze0

Would you please consider this PR? Thanks in advance 🙏

**Pull request merged**
