### PR TITLE
Use manifestival to reconcile Shipwright Builds

### PR DESCRIPTION
**Pull request by adambkaplan**
# Changes

- Add v0.4.0 release YAML as the manifest to reconcile
- main.go - Add CRD APIs to the client scheme
- Update controller to use manifest for reconciliation:
  - If ShipwrightBuild object is created or updated, apply manifest
  - If ShipwrightBuild object is deleted, use manifest to delete objects
- Add integration tests to verify Shipwright Build is installed.
- Add kubebuilder annotations to grant the operator permissions that
  Shipwright build requests.
- Regenerate rbac manifest for operator.
- Change default kustomization rule to install operator into the
  `shipwright-operator` namespace.
- Rename primary container to "operator", use default entrypoint for
  command.
- Document how to deploy the operator to a local Kubernetes cluster for
testing purposes.

/kind feature

# Submitter Checklist

- [x] Includes tests if functionality changed/was added
- [x] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/master/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Shipwright Build APIs and controller are installed if a ShipwrightBuild object is created on the cluster.
When created, Shipwright's controller is installed in the `shipwright-build` namespace.
This namespace must be created beforehand.

When a ShipwrightBuild object is deleted, the controller and APIs are subsequently removed from the cluster.
```

### CODE REVIEW

**Comment by adambkaplan** [comment]
/approve

Self-approving

**Review by ImJasonH — APPROVED** [review]

**Comment by adambkaplan** [comment]
@ImJasonH if you intended to give the thumbs up for merge, you need to use the prow "/lgtm" command :smile:

**Comment by ImJasonH** [comment]
Whoops!

/lgtm

**Pull request merged**
