### PR TITLE
Upgrade shipwright-io/build to v0.13.0

### PR DESCRIPTION
**Pull request by adambkaplan**
# Changes

Upgrade shipwright-io/build to v0.13.0, ahead of upgrading the samples and operand deployments.

This includes respective transitive updates to k8s libraries and their dependencies. As part of the upgrade, a previously identified flaky/brittle test started failing permanently. These have been skipped for the interim.

These updates also exposed a bug in the controller code, where the controller would not re-queue when a status update failed. This has now been fixed.

/kind cleanup

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Upgrade shipwright-io/build code dependencies to v0.13.0 and k8s.io to v0.27.11. These upgrades exposed a bug in the controller code, where failure to update the ShipwrightBuild object status would not trigger a requeue. This was fixed so status update failures cause the controller to re-reconcile.
```

### CODE REVIEW

**Comment by apoorvajagtap** [comment]
@adambkaplan I believe there's a typo in k8s.io version mentioned in the release note, it should be v0.27.11 instead of v1.27.11, right?

Also, the unit test failures report 
`unable to retrieve the complete list of server APIs: shipwright.io/v1alpha1`
As we now have set the storage version to v1beta1 with build v0.13.0, we need to update the buildStrategy samples [here](https://github.com/shipwright-io/operator/tree/main/kodata/samples/buildstrategy) similar to [build/samples/v1beta1](https://github.com/shipwright-io/build/tree/main/samples/v1beta1/buildstrategy).

**Review by apoorvajagtap — CHANGES_REQUESTED** [review]
@adambkaplan I believe there's a typo in k8s.io version mentioned in the release note, it should be v0.27.11 instead of v1.27.11, right?

Also, the unit test failures report
`unable to retrieve the complete list of server APIs: shipwright.io/v1alpha1`
As we now have set the storage version to v1beta1 with build v0.13.0, we need to update the buildStrategy samples [here](https://github.com/shipwright-io/operator/tree/main/kodata/samples/buildstrategy) similar to [build/samples/v1beta1](https://github.com/shipwright-io/build/tree/main/samples/v1beta1/buildstrategy).

**Comment by adambkaplan** [comment]
/kind bug

:relieved: these updates actually exposed a bug in the controller code! I observed a few things that led me to think something was off in the tests:

1. We were still deploying Shipwright v0.12 operands, so the switch from v1alpha1 to v1beta1 storage should not be an issue.
2. The test was failing because of an API discovery error during the setup phase - the code to check if the build strategies API existed was returning early. I suspected this was happening because we had API skew between EnvTest and our k8s.io client code. Changing EnvTest to use k8s 1.27 seems to have fixed this.
3. I _separately_ saw in the test logs that we were getting a "conflict" error from EnvTest. This isn't totally weird for a controller - I've seen it plenty of times in other controller logs, especially if the controller is not using server-side apply. What was weird was that there was no follow-up re-queue in the test logs. This led me to a very important 1-line bug fix.

Release note has been updated to include this bug fix.

**Review by apoorvajagtap — APPROVED** [review]

**Comment by adambkaplan** [comment]
/approve

Self-approving. TODO - may need to review DevStats to add additional approvers.

**Pull request merged**
