### PR TITLE
Updated go modules to 1.21

### LINKED ISSUE #189: [FEATURE] Update to Go 1.21
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

[Go 1.20 is end of support already.](https://endoflife.date/go)

### Describe the solution that you would like.

We should update go.mod and CI to use Go 1.21. PR should be similar to [the last one](https://github.com/shipwright-io/operator/pull/161).

### Describe alternatives you have considered.

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Adarsh-jaiss**
# Changes
- Updated the Go mod version to 1.21
- fixes #189 

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [ ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [ ] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

### CODE REVIEW

**Review by adambkaplan — COMMENTED** [review]
/approve

Giving the :+1: that we should update the golang version to 1.21. However, the CI GitHub action workflow also needs to be updated to use golang 1.21 (it currently uses 1.20)

In addition, @Adarsh-jaiss please ensure the pull request has a proper release note block, noting that we have updated the golang version to 1.21

**Comment by qu1queee** [comment]
@Adarsh-jaiss pls also help with the CI bump, see https://github.com/shipwright-io/operator/blob/main/.github/workflows/ci.yml#L21

**Comment by Adarsh-jaiss** [comment]
@qu1queee Do I also need to update the release.yaml file? 
Here: https://github.com/shipwright-io/operator/blob/e714be739483ab4b55a18ad863100dc8158fbbf1/.github/workflows/release.yaml#L32

**Comment by SaschaSchwarze0** [comment]
> Thank you so much @qu1queee for pointing it out. I have fixed it. Also I have a question, Do we also need to update the release.yaml file? Here:
> 
> https://github.com/shipwright-io/operator/blob/e714be739483ab4b55a18ad863100dc8158fbbf1/.github/workflows/release.yaml#L32

Yes

**Comment by Adarsh-jaiss** [comment]
Hey @SaschaSchwarze0 , I have made the significant changes, kindly review it once and please let me the further improvements to make if required :)

**Review by SaschaSchwarze0 — CHANGES_REQUESTED** [review]
Thanks @Adarsh-jaiss, your changes all look good. May you have a look at the changes from the previous PR where the bump to 1.20 was done: https://github.com/shipwright-io/operator/pull/161/files

There are a few developer docs that also mention the Go version that are worth getting updates as well.

Thank you in advance.

**Comment by Adarsh-jaiss** [comment]
> Thanks @Adarsh-jaiss, your changes all look good. May you have a look at the changes from the previous PR where the bump to 1.20 was done: https://github.com/shipwright-io/operator/pull/161/files
> 
> There are a few developer docs that also mention the Go version that are worth getting updates as well.
> 
> Thank you in advance.

Thank you so much @SaschaSchwarze0 , I have done the changes and also updated the Ko version to v0.15.2 :) 
Please let me the know, if there are any other changes to make :)

**Review by SaschaSchwarze0 — APPROVED** [review]
/approve
/lgtm

Thank you.

**Pull request merged**
