### PR TITLE
Update Shipwright Build to v0.11.0

### PR DESCRIPTION
**Pull request by adambkaplan**
# Changes

- Update deployment to use Build v0.11.0
- Update version of the operator

/kind feature

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [x] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/master/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Update deployment of Shipwright Build to v0.11.0
```

### CODE REVIEW

**Review by SaschaSchwarze0 — CHANGES_REQUESTED** [review]
Can you also update the version in https://github.com/shipwright-io/operator/blob/main/docs/shipwrightbuild.md.

**Comment by adambkaplan** [comment]
> Can you also update the version in https://github.com/shipwright-io/operator/blob/main/docs/shipwrightbuild.md.

Done!

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Comment by adambkaplan** [comment]
/approve

Self-approving.

**Pull request merged**
